personal_finance_pipeline:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('PROJECT_ID') }}"
      dataset: silver
      location: US
      threads: 4
      keyfile_json: "{{ env_var('GCP_SA_KEY_JSON') }}"
